services:
  php:
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./docker/php/conf.d/xdebug.dev.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./docker/php/conf.d/opcache.dev.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"